/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Hello");
        return true;
    }
}
